# mkdocs.yml
site_name: Library System Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Library System Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
